# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-03 06:14
from __future__ import unicode_literals

import decals.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Decal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('is_active', models.BooleanField(default=True)),
                ('is_updated', models.BooleanField(default=False)),
                ('image', models.FileField(upload_to=decals.models.update_filename_decal)),
            ],
            options={
                'db_table': 'Decal',
            },
        ),
        migrations.CreateModel(
            name='DecalCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('is_active', models.BooleanField(default=True)),
                ('is_updated', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'DecalCategory',
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('number', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_updated', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Part',
            },
        ),
        migrations.CreateModel(
            name='PartSide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('top', 'Top'), ('bottom', 'Bottom'), ('left', 'Left'), ('right', 'Right')], max_length=6)),
                ('no_of_decals', models.IntegerField()),
                ('template_number', models.IntegerField()),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('Revised_on', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_updated', models.BooleanField(default=False)),
                ('image', models.FileField(upload_to=decals.models.update_filename_side)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='decals.Part')),
            ],
            options={
                'db_table': 'PartSide',
            },
        ),
        migrations.CreateModel(
            name='PartSideDecal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_updated', models.BooleanField(default=False)),
                ('decal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='decals.Decal')),
                ('part_side', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='decals.PartSide')),
            ],
            options={
                'db_table': 'PartSideDecal',
            },
        ),
        migrations.AddField(
            model_name='decal',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='decals.DecalCategory'),
        ),
        migrations.AlterUniqueTogether(
            name='partside',
            unique_together=set([('part', 'side')]),
        ),
    ]
